services:
  - type: web
    name: cuadrantes-app
    runtime: static
    plan: free
    rootDir: Varios/Cuadrantes/cuadrantes-app
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
